# Generated by Django 3.0.5 on 2020-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='priority',
            field=models.SmallIntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
