# Generated by Django 3.0.5 on 2020-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='priority',
            field=models.SmallIntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
