# Generated by Django 3.0.5 on 2020-04-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0002_listitem_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='expare_date',
            new_name='expire_date',
        ),
    ]
