# Generated by Django 3.0.5 on 2020-05-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200430_1851'),
        ('list_item', '0003_auto_20200430_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('name', 'list', 'expire_date')},
        ),
    ]
